<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706121417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, salle VARCHAR(50) DEFAULT NULL, heure_debut VARCHAR(5) NOT NULL, heure_fin VARCHAR(5) NOT NULL, jour_semaine INT NOT NULL, is_annule BOOLEAN NOT NULL, matiere_id INT NOT NULL, classe_id INT DEFAULT NULL, enseignant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FDCA8C9CF46CD258 ON cours (matiere_id)');
        $this->addSql('CREATE INDEX IDX_FDCA8C9C8F5EA509 ON cours (classe_id)');
        $this->addSql('CREATE INDEX IDX_FDCA8C9CE455FCC0 ON cours (enseignant_id)');
        $this->addSql('CREATE TABLE devoir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_rendu DATE NOT NULL, urgent BOOLEAN NOT NULL, matiere_id INT DEFAULT NULL, classe_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_749EA771F46CD258 ON devoir (matiere_id)');
        $this->addSql('CREATE INDEX IDX_749EA7718F5EA509 ON devoir (classe_id)');
        $this->addSql('ALTER TABLE cours ADD CONSTRAINT FK_FDCA8C9CF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cours ADD CONSTRAINT FK_FDCA8C9C8F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE cours ADD CONSTRAINT FK_FDCA8C9CE455FCC0 FOREIGN KEY (enseignant_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA771F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE devoir ADD CONSTRAINT FK_749EA7718F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cours DROP CONSTRAINT FK_FDCA8C9CF46CD258');
        $this->addSql('ALTER TABLE cours DROP CONSTRAINT FK_FDCA8C9C8F5EA509');
        $this->addSql('ALTER TABLE cours DROP CONSTRAINT FK_FDCA8C9CE455FCC0');
        $this->addSql('ALTER TABLE devoir DROP CONSTRAINT FK_749EA771F46CD258');
        $this->addSql('ALTER TABLE devoir DROP CONSTRAINT FK_749EA7718F5EA509');
        $this->addSql('DROP TABLE cours');
        $this->addSql('DROP TABLE devoir');
    }
}
