<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703220007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(50) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_account_id INT DEFAULT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9EF0AD163C0C9956 ON event_log (user_account_id)');
        $this->addSql('CREATE INDEX IDX_9EF0AD16FF631228 ON event_log (etablissement_id)');
        $this->addSql('ALTER TABLE event_log ADD CONSTRAINT FK_9EF0AD163C0C9956 FOREIGN KEY (user_account_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE event_log ADD CONSTRAINT FK_9EF0AD16FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_log DROP CONSTRAINT FK_9EF0AD163C0C9956');
        $this->addSql('ALTER TABLE event_log DROP CONSTRAINT FK_9EF0AD16FF631228');
        $this->addSql('DROP TABLE event_log');
    }
}
