<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706200229 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, fichier VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, couleur VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, matiere_id INT DEFAULT NULL, uploader_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76F46CD258 ON document (matiere_id)');
        $this->addSql('CREATE INDEX IDX_D8698A7616678C77 ON document (uploader_id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7616678C77 FOREIGN KEY (uploader_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76F46CD258');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7616678C77');
        $this->addSql('DROP TABLE document');
    }
}
