<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905113205 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE demande_modification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, champ VARCHAR(100) NOT NULL, nouvelle_valeur VARCHAR(500) NOT NULL, message VARCHAR(1000) DEFAULT NULL, justificatif_path VARCHAR(500) DEFAULT NULL, statut VARCHAR(20) NOT NULL, traite_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, commentaire_admin VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, demandeur_id INT NOT NULL, traite_par_id INT DEFAULT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8ADB7A895A6EE59 ON demande_modification (demandeur_id)');
        $this->addSql('CREATE INDEX IDX_B8ADB7A8167FABE8 ON demande_modification (traite_par_id)');
        $this->addSql('CREATE INDEX IDX_B8ADB7A8FF631228 ON demande_modification (etablissement_id)');
        $this->addSql('ALTER TABLE demande_modification ADD CONSTRAINT FK_B8ADB7A895A6EE59 FOREIGN KEY (demandeur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_modification ADD CONSTRAINT FK_B8ADB7A8167FABE8 FOREIGN KEY (traite_par_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE demande_modification ADD CONSTRAINT FK_B8ADB7A8FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE demande_modification DROP CONSTRAINT FK_B8ADB7A895A6EE59');
        $this->addSql('ALTER TABLE demande_modification DROP CONSTRAINT FK_B8ADB7A8167FABE8');
        $this->addSql('ALTER TABLE demande_modification DROP CONSTRAINT FK_B8ADB7A8FF631228');
        $this->addSql('DROP TABLE demande_modification');
    }
}
