<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623222950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE absence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, heure_debut TIME(0) WITHOUT TIME ZONE DEFAULT NULL, heure_fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL, motif VARCHAR(255) DEFAULT NULL, justifiee BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, eleve_id INT NOT NULL, saisie_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_765AE0C9A6CC7B2 ON absence (eleve_id)');
        $this->addSql('CREATE INDEX IDX_765AE0C9C74AC7FE ON absence (saisie_par_id)');
        $this->addSql('CREATE TABLE matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL, coefficient DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valeur DOUBLE PRECISION NOT NULL, commentaire VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note_sur DOUBLE PRECISION DEFAULT NULL, eleve_id INT NOT NULL, professeur_id INT NOT NULL, matiere_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFBDFA14A6CC7B2 ON note (eleve_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14BAB22EE9 ON note (professeur_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14F46CD258 ON note (matiere_id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9A6CC7B2 FOREIGN KEY (eleve_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9C74AC7FE FOREIGN KEY (saisie_par_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14A6CC7B2 FOREIGN KEY (eleve_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14BAB22EE9 FOREIGN KEY (professeur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absence DROP CONSTRAINT FK_765AE0C9A6CC7B2');
        $this->addSql('ALTER TABLE absence DROP CONSTRAINT FK_765AE0C9C74AC7FE');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14A6CC7B2');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14BAB22EE9');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14F46CD258');
        $this->addSql('DROP TABLE absence');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE note');
    }
}
