<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260826084641 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appreciation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, periode VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, eleve_id INT NOT NULL, professeur_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5CD4DEABA6CC7B2 ON appreciation (eleve_id)');
        $this->addSql('CREATE INDEX IDX_5CD4DEABBAB22EE9 ON appreciation (professeur_id)');
        $this->addSql('CREATE INDEX IDX_5CD4DEABF46CD258 ON appreciation (matiere_id)');
        $this->addSql('CREATE INDEX IDX_5CD4DEABFF631228 ON appreciation (etablissement_id)');
        $this->addSql('CREATE TABLE retard (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, duree VARCHAR(255) DEFAULT NULL, motif VARCHAR(255) DEFAULT NULL, justifie BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, eleve_id INT NOT NULL, saisiepar_id INT DEFAULT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C64DDBDA6CC7B2 ON retard (eleve_id)');
        $this->addSql('CREATE INDEX IDX_5C64DDBDBCEBF3E2 ON retard (saisiepar_id)');
        $this->addSql('CREATE INDEX IDX_5C64DDBDFF631228 ON retard (etablissement_id)');
        $this->addSql('CREATE TABLE sanction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, motif TEXT DEFAULT NULL, date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, eleve_id INT NOT NULL, saisiepar_id INT DEFAULT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D6491AFA6CC7B2 ON sanction (eleve_id)');
        $this->addSql('CREATE INDEX IDX_6D6491AFBCEBF3E2 ON sanction (saisiepar_id)');
        $this->addSql('CREATE INDEX IDX_6D6491AFFF631228 ON sanction (etablissement_id)');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEABA6CC7B2 FOREIGN KEY (eleve_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEABBAB22EE9 FOREIGN KEY (professeur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEABF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEABFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('ALTER TABLE retard ADD CONSTRAINT FK_5C64DDBDA6CC7B2 FOREIGN KEY (eleve_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE retard ADD CONSTRAINT FK_5C64DDBDBCEBF3E2 FOREIGN KEY (saisiepar_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE retard ADD CONSTRAINT FK_5C64DDBDFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('ALTER TABLE sanction ADD CONSTRAINT FK_6D6491AFA6CC7B2 FOREIGN KEY (eleve_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sanction ADD CONSTRAINT FK_6D6491AFBCEBF3E2 FOREIGN KEY (saisiepar_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE sanction ADD CONSTRAINT FK_6D6491AFFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appreciation DROP CONSTRAINT FK_5CD4DEABA6CC7B2');
        $this->addSql('ALTER TABLE appreciation DROP CONSTRAINT FK_5CD4DEABBAB22EE9');
        $this->addSql('ALTER TABLE appreciation DROP CONSTRAINT FK_5CD4DEABF46CD258');
        $this->addSql('ALTER TABLE appreciation DROP CONSTRAINT FK_5CD4DEABFF631228');
        $this->addSql('ALTER TABLE retard DROP CONSTRAINT FK_5C64DDBDA6CC7B2');
        $this->addSql('ALTER TABLE retard DROP CONSTRAINT FK_5C64DDBDBCEBF3E2');
        $this->addSql('ALTER TABLE retard DROP CONSTRAINT FK_5C64DDBDFF631228');
        $this->addSql('ALTER TABLE sanction DROP CONSTRAINT FK_6D6491AFA6CC7B2');
        $this->addSql('ALTER TABLE sanction DROP CONSTRAINT FK_6D6491AFBCEBF3E2');
        $this->addSql('ALTER TABLE sanction DROP CONSTRAINT FK_6D6491AFFF631228');
        $this->addSql('DROP TABLE appreciation');
        $this->addSql('DROP TABLE retard');
        $this->addSql('DROP TABLE sanction');
    }
}
